### ISSUE TITLE
Typewriter sounds problem

### ISSUE THREAD

**Issue by JC333** [gottcode/focuswriter#168]
There are no sounds when I type. I used to use Focuswriter, possibly with a different Windows version, (currently using 8.1) and the sounds worked fine at that time. Can you help with this?

**Comment by gottcode** [comment]
That is very odd. As a test, I just ran the installer for FocusWriter, as well as extracted the portable one, and the sounds work fine for me in Windows 8.1 in both setups. Are you sure you have them enabled? They aren't by default anymore.

By the way, thank you for opening a new issue. The other GitHub issue is a feature request purely about making the sounds more realistic. In general, for open source projects bug report or feature request should cover a single issue, not an entire topic.

**Comment by JC333** [comment]
Yes it's enabled. Settings - Preferences - ticked for Typewriter Sounds.
I've got version 1.5.4

It's annoying because I've just started writing in earnest and I really
used to find the Sounds helpful, it seemed to keep me in a rhythm and I
made less typos and errors! Let me know if you think of anything.

John

**Comment by gottcode** [comment]
I have not been able to recreate this myself; sounds always work for me on all platforms. Because of that I have not been able to fix whatever may be causing the problem.

However, I just made a bugfix release (version 1.5.5) that switched back to dynamic libraries, and that may be related. Would you mind checking if that version still doesn't play sounds?

**Comment by JC333** [comment]
Hi Graeme

Seem to have got the sounds back!

I was just looking in my Start Up and did a search for Focuswriter, I then
clicked on keyany_wav and found that the import button for the focuswriter
sounds. Then installed FW again and the sound as back.

Don't know if it was down to what I did or not???

John

**Comment by gottcode** [comment]
Well, I'm glad to hear that the sounds are back! I'm not sure what you mean by an "import button" for sounds... When you installed it again, which version did you install?

**Comment by JC333** [comment]
Here's a screenshot of where I clicked on Import, I ticked the box first:
[image: Inline image 1]

The version is 1.5.4

John

**Comment by gottcode** [comment]
Unfortunately, the image didn't get transmitted to GitHub. You can either edit your comment, or email it to me directly.

Interesting to know that the audio issue resolved itself without you having to upgrade to the latest version.

**Comment by JC333** [comment]
Don't know your own email address so I'll try sending it as an attachment.

John

**Comment by gottcode** [comment]
Sorry, didn't work. I guess you will have to comment directly on GitHub instead of replying through email, as I know you can include images in GitHub comments.

**Comment by Raltorio** [comment]
I have a similar problem with Focuswriter as well.  I had and have been using version 1.4.0 and sounds work but then on a whim looked to see if there had been some updates and there was/is now version 1.5.5 and decided to install that.  In Windows 7, the optional sounds do not work.  Placing a 'Data' directory in the executable directory makes no difference.  I thought perhaps the previous install was interfering so deleted that and it made no difference.  I tried various compatibility modes like Vista or XP and that made no difference.  In the end, because the sounds soothe me I re-installed version 1.4.0 to have the sounds working.  However, all the titles of the themes were changed to some arcane code string so deleted them all.

I would much like to update the version since it now creates an entry in the start menu and includes an uninstaller however, it would be nice if the sounds worked.  I find myself exceedingly curious as to what was 'enabled' by JC333.

Thank you.
