### ISSUE TITLE
GTK integration with -style=gtk

### ISSUE THREAD

**Issue by orschiro** [gottcode/focuswriter#173]
Dear @gottcode,

Thank you so much for your work on focuswriter! It's an excellent tool. I am working on elementaryOS which is based on Ubuntu 14.04. It uses GTK as its environment instead of Qt. 

By default Focuswriter does not nicely integrate into the GTK environment:

![image](https://cloud.githubusercontent.com/assets/170947/9434310/a7c57cd4-4a3d-11e5-8345-dd58063246cc.png)

I googled and found [this](http://www.itsprite.com/linux-qtconfig-tool-for-qt-5/) source which states that a basic integration can be achieved by launching focuswriter with `-style=gtk`. Indeed it makes the menu, for instance, much more appealing:

![image](https://cloud.githubusercontent.com/assets/170947/9434330/ec57695c-4a3d-11e5-9223-67cb6f40148f.png)

I am wondering how I can make this setting permanent so that I don't have to append this option on the command line every time I want to launch focuswriter. Instead I prefer to launch focuswriter from the application menu. 

I thought I can add this option to `/usr/share/applications/focuswriter.desktop`:

```
TryExec=/usr/bin/focuswriter -style=gtk
Exec=/usr/bin/focuswriter -style=gtk %F
```

But after doing that, FocusWriter no longer shows up in the menu. Do you have any idea why and how I can make this style setting permanent?

Thankfully,

Robert

**Comment by gottcode** [comment]
Unfortunately, I have no idea why it would stop showing up in the menu. That looks like the correct form for the desktop file (although I don't think you should pass ```-style=gtk``` to ```TryExec```, since that is just to look for the executable).

While I can see the desire to specify the style just for FocusWriter, wouldn't it be better to get Qt to always use the GTK style? The simplest way I can think of to do that would be to set the environment variable ```QT_STYLE_OVERRIDE``` to ```gtk```. I would recommend setting that value in something that gets parsed globally, such as a script in ```/etc/profile.d```.

A more invasive approach would be to patch Qt and inform it that elementaryOS's desktop environment uses GTK. That would required modifying the file ```qtbase/src/platformsupport/themes/genericunix/``` to check the ```DESKTOP_SESSION``` environment variable for whatever it is set to in elementaryOS.

**Comment by orschiro** [comment]
> While I can see the desire to specify the style just for FocusWriter, wouldn't it be better to get Qt to always use the GTK style? The simplest way I can think of to do that would be to set the environment variable QT_STYLE_OVERRIDE to gtk. I would recommend setting that value in something that gets parsed globally, such as a script in /etc/profile.d.

Thanks for your solution! For other who find this issue, there is also another solution provided on [elementaryOS StackExchange](http://elementaryos.stackexchange.com/questions/1240/how-to-set-qt-style-to-default).
