### ISSUE TITLE
Doesn't scale when using Ubuntu's scaling functionality for HiDPI displays

### ISSUE THREAD

**Issue by CreamyCookie** [gottcode/focuswriter#181]
FocusWriter doesn't scale when using [Ubuntu's scaling functionality](http://askubuntu.com/questions/472262/adapt-ubuntu-to-a-high-dpi-resolution-screen/472266#472266), which is mainly used on HiDPI monitors, where the text would otherwise be too small due to high pixel density. This probably also applies to other distributions with such functionality.

![hidpi](https://cloud.githubusercontent.com/assets/3063858/11076952/e1376dbc-87fd-11e5-9133-1101943d8562.png)

Here's another example that shows a confirmation dialogue, which also isn't scaled. (The title bar text is though.)

![confirm](https://cloud.githubusercontent.com/assets/3063858/11077261/79cf94f4-87ff-11e5-9f13-eaa890d392ee.png)

**Comment by gottcode** [comment]
FocusWriter doesn't yet support HiDPI at all. It will eventually, but as of right now it doesn't. Sorry.

**Comment by CreamyCookie** [comment]
@gottcode Oh okay, but why do you close the bug report? Shouldn't it stay open, until it's fixed?

**Comment by gottcode** [comment]
It's not a matter of fixing a bug; it is a much more involved process of modifying lots of separate code. I don't consider it a bug--it is a feature I haven't added yet.

**Comment by CreamyCookie** [comment]
I guess it could be seen this way.

> a program not doing something it is supposed to do

I'd argue that in this day and age, it is supposed to support HiDPI. (Of course you're free to disagree.)

And, even if not, `feature requests` are also often tracked using the issue tracker, by tagging them so.

Anyway, thanks for this program :+1:

**Comment by gottcode** [comment]
I knew I should have been more careful about phrasing; that is not what I meant at all. If a program is written to do something, *but it doesn't do that something*, that's a bug. Not just a generic "it should do this". That is a feature request, never a bug.

This GitHub Issue was written as a bug report about a feature not working--a feature FocusWriter doesn't have--which is why I closed it. Feel free to open a new one that is a feature request to add HiDPI support, sure. There are plenty of feature requests for FocusWriter open right now.

**Comment by CreamyCookie** [comment]
Well, you could've told me from the beginning. Done: #183 :smiley:
